### ISSUE TITLE
Issue with libraryfolders.vdf

### ISSUE THREAD

**Issue by michalss** [shravan2x/Gameloop.Vdf#15]
Hi how can i do deserialization on that pls. It seems that it could be array.. But how to assign 1 to json model ??

"LibraryFolders"
{
	"TimeNextStatsReport"		"1578345576"
	"ContentStatsID"		"-9082669944124938900"
	"1"		"D:\\Games"
}

**Comment by shravan2x** [comment]
It doesn't look like an array to me since it has other properties like `TimeNextStatsReport`. Do you get an error when trying to deserialize it?

**Comment by Velkas** [comment]
I'm trying the same thing. the Value is valid and contains the entire set of data which can be printed. But explicit access to each keyvalue pair is not available. I want to read the library file and get all the available library locations from it, so I can dynamically know where the user has any libraries that might have installed games.

```
if (File.Exists(libFile))
{
  var steam = VdfConvert.Deserialize(File.ReadAllText(libFile));
  Console.WriteLine(steam.Value);
}
```

will output

```
{
        "TimeNextStatsReport" "1580329161"
        "ContentStatsID" "3733404908572595093"
        "1" "D:\SteamLibrary"
        "2" "E:\SteamLibrary"
}
```



----------------------------
Actually, I solved it. I can access them via the Children() method on Value. @michlss I hope that helps!

`Console.WriteLine(steam.Value.Children().First());`

**Comment by shravan2x** [comment]
@Velkas The behavior here is similar to that of Json.NET. You can also do this:

```c#
VObject obj = steam.Value as VObject;
Console.WriteLine(obj["TimeNextStatsReport"].Value<string>());
```

The value of a `VProperty` (i.e. `steam.Value` in your example) is always `VToken` since the type system doesn't know whether it is a `VObject` or a `VValue`. However, if you know for a _specific_ VDF file that it will be an object, you can just cast it as such.

You can also use `dynamic` similar to how Json.NET uses it.
