### ISSUE TITLE
Values containing '\' character are not parsed properly

### ISSUE THREAD

**Issue by RadCraftplay** [shravan2x/Gameloop.Vdf#28]
When I try to parse text:

```
"Config"
{
	"Games"	"Some\text"
}
```

With code:

```cs
var text = "\"Config\"\n{\n    \"Games\"    \"Some\\text\"\n}";
var config = VdfConvert.Deserialize(text);
var games = config.Value["Games"];
```

Value "Games" is parsed as "some\text" instead of "some\\\text" (if you "Console.Write" this you get "some	ext").

**Comment by shravan2x** [comment]
I believe this is an error in the VDF file itself if it uses escape sequences. It should have been written as "some\\\\text" and would have been parsed correctly.

However, Valve's own VDF parser has an option to disable escape sequences. So it's possible some VDF files just don't support them. In this library, support for escape sequences is enabled by default, but this can be changed by setting [`UsesEscapeSequences`](https://github.com/shravan2x/Gameloop.Vdf/blob/master/Gameloop.Vdf/VdfSerializerSettings.cs#L15) to `false`. Or simply by using `var config = VdfConvert.Deserialize(text, VdfSerializerSettings.Default);`.

The naming for the two `VdfSerializerSettings` might seem counter-intuitive since `VdfSerializerSettings.Default` is actually not the default, but rather `VdfSerializerSettings.Common`. This is because `VdfSerializerSettings.Default` refers to the defaults in Valve's own VDF parser, not the defaults of this library. In my experience, it's far more common for users to encounter VDF files that use escape sequences, so the default of this library is `VdfSerializerSettings.Common` instead.

**Comment by RadCraftplay** [comment]
Thanks for help! Problem solved!
