### ISSUE TITLE
How to properly traverse deserialized data?

### ISSUE THREAD

**Issue by TheRdMelon** [shravan2x/Gameloop.Vdf#7]
Trying to traverse the items_game.txt file for CS:GO.  As an example I'll try to get to "first_valid_class" under "game_info".
I can do it using an older method from reading an old issue:
```
dynamic itemsG = VdfConvert.Deserialize(itemsGame);

Log.Info(itemsG.Value["game_info"]["first_valid_class"].ToString());
```

But when I try to use what I think is a new method that you added, meant to be more like json:
```
Log.Info(itemsG.game_info.first_valid_class.ToString());
```
It throws an excpetion: "'Gameloop.Vdf.Linq.VProperty' does not contain a definition for 'game_info'".
What am I getting wrong?  It's not clear how to use it from the README file, you use '.Valve' despite nothing in the example being called "Valve".

EDIT: Never mind, all of 5 minutes later and re-read the documentation and saw it says "Value", not "Valve".  It now works.  However on the documentation you state that you skipped the enclosing property name "Steam", but I still have to include "game_info".  What's going on?

**Comment by shravan2x** [comment]
When You call `VdfConvert.Deserialize(itemsGame)`, the function returns a `VProperty`. This `VProperty` refers to the root element "Steam". You don't need to refer to this in your code since there can only ever be one root property, which you already have.

Your confusion is justified in that the first time you need to use `.Value` since you have a `VProperty`. But as you access child elements, the library directly returns their values.

From a technical standpoint, it is fully possible to directly return the value of the root property instead of the property itself. But this has one serious limitation - it would be impossible to find the key name of the root property.

Imagine some use case where you need to know the name of the root element (i.e. "Steam" in the below example):
```
"Steam"
{
	"SSAVersion"		"3"
	"PrivacyPolicyVersion"		"2"
	"SteamDefaultDialog"		"#app_store"
	"DesktopShortcutCheck"		"0"
	"StartMenuShortcutCheck"		"0"
}
```

Using the code we have now, you could simply do `VdfConvert.Deserialize(vdfData).Key`. If we had directly returned a `VObject` that represented the value of the property, then getting the key name would be impossible.

Coming back to your question, you need to use `.Value` on the root property since there is no other way to find the `.Key` if you ever need it. However, for descendants, this will never be a problem since you already know the key name when you access it!

I understand this might sound even more confusing - let me know if I can help clear anything up.

**Comment by shravan2x** [comment]
As a final complication, it is actually possible to have the best of both worlds by allowing all these 3 pieces of code below to work together:

### **NOTE: This is not valid code in the current version of the library. It is only a thought experiment !!!**
```
dynamic obj = VdfConvert.Deserialize(vdfData);
Console.WriteLine(obj.Key); // Prints "Steam"
Console.WriteLine(obj.SSAVersion); // Prints "3"
Console.WriteLine(obj.Value.SSAVersion); // Prints "3"
```

This could be done by making the `VProperty` type check if a dynamically accessed property is either `Key` or `Value` and if not, then to try and access it from the value directly (iff the `.Value` is a `VObject`). But I felt this would only lead to more confusion (imagine a case where the value of the property is a `VObject` that also contains a property with a key named "Key").

Note that JSON doesn't have to deal with this problem at all since properties are not valid root elements. While implementing this library, I had to make a decision and decided on this since I thought it would most closely match the behavior of JSON.NET.

**Comment by TheRdMelon** [comment]
Thank you.  I don't think that was more confusing, it cleared it up for me and I understand it now.
